import type {
  ClimbingRoute,
  holdType,
  JSONClimbingRoute,
  routeProtection,
} from "../types";

const JSON_TEMP_CLIMBING_ROUTES: JSONClimbingRoute[] = [
  {
    id: 1,
    name: "Crimson Traverse",
    img: "/generic_route_4.jpg",
    grade: "V8",
    gradeSystem: "V",
    difficulty: 17,
    routeProtection: "Boulder",
    holdColor: "Teal",
    holdType: "Crimps",
    gym: 1,
    setter: "Charlotte U.",
    attempts: 28,
    dateSet: "2023-08-25T01:31:39Z",
    mostRecentAttempt: "2024-06-25T01:31:39Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "This Crimson Traverse is a beast! Still projecting the crux, needs more finger strength.",
    routeAttributes: ["Traverse", "Arete"],
  },
  {
    id: 2,
    name: "Blue Sky Slab",
    img: "/generic_route_2.jpg",
    grade: "5.10a",
    gradeSystem: "YDS",
    difficulty: 7,
    routeProtection: "Top Rope",
    holdColor: "Blue",
    holdType: "Pinches",
    gym: 2,
    setter: "Alexander R.",
    attempts: 26,
    dateSet: "2023-06-03T18:03:07Z",
    mostRecentAttempt: "2025-02-12T18:03:07Z",
    complete: true,
    dateComplete: "2025-02-12T18:28:07Z",
    project: false,
    notes: "Sent this one! Flowy and fun, felt solid. Good warm-up route.",
    routeAttributes: ["Slab"],
  },
  {
    id: 3,
    name: "Emerald Ascent",
    img: "/generic_route_3.jpg",
    grade: "7a",
    gradeSystem: "French",
    difficulty: 14,
    routeProtection: "Lead",
    holdColor: "Pink",
    holdType: "Slopers",
    gym: 3,
    setter: "Michael X.",
    attempts: 27,
    dateSet: "2023-08-20T17:15:39Z",
    mostRecentAttempt: "2025-06-11T17:15:39Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "Making slow progress on Emerald Ascent. That dyno is a commitment, still working on the landing.",
    routeAttributes: ["Overhang", "Traverse"],
  },
  {
    id: 4,
    name: "Sunset Crack",
    img: "/generic_route_5.jpg",
    grade: "5.9",
    gradeSystem: "YDS",
    difficulty: 6,
    routeProtection: "Lead",
    holdColor: "Grey",
    holdType: "Cracks",
    gym: 4,
    setter: "Emma K.",
    attempts: 7,
    dateSet: "2023-07-28T04:22:20Z",
    mostRecentAttempt: "2025-04-18T04:22:20Z",
    complete: true,
    dateComplete: "2025-04-18T05:07:20Z",
    project: false,
    notes:
      "Cracked it! The beta clicked after a few tries. Really enjoyed this one.",
    routeAttributes: ["Crack"],
  },
  {
    id: 5,
    name: "Purple Haze Boulder",
    img: "/generic_route_8.jpg",
    grade: "V3",
    gradeSystem: "V",
    difficulty: 7,
    routeProtection: "Boulder",
    holdColor: "Green",
    holdType: "Volumes",
    gym: 5,
    setter: "Liam Q.",
    attempts: 13,
    dateSet: "2024-03-08T03:52:19Z",
    mostRecentAttempt: "2025-03-10T03:52:19Z",
    complete: true,
    dateComplete: "2025-03-10T04:36:19Z",
    project: false,
    notes: "Sent this one! Flowy and fun, felt solid. Good warm-up route.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 6,
    name: "Golden Arete",
    img: "/generic_route_7.jpg",
    grade: "5.11b",
    gradeSystem: "YDS",
    difficulty: 12,
    routeProtection: "Top Rope",
    holdColor: "Yellow",
    holdType: "Slopers",
    gym: 6,
    setter: "Isabella V.",
    attempts: 3,
    dateSet: "2023-11-23T11:58:39Z",
    mostRecentAttempt: "2025-01-22T11:58:39Z",
    complete: false,
    dateComplete: "undefined",
    project: false,
    notes: "Need to clean up the middle part. Getting closer to a send.",
    routeAttributes: ["Arete"],
  },
  {
    id: 7,
    name: "Phantom Slab",
    img: "/generic_route_1.jpg",
    grade: "6c+",
    gradeSystem: "French",
    difficulty: 13,
    routeProtection: "Boulder",
    holdColor: "Black",
    holdType: "Pinches",
    gym: 7,
    setter: "Evelyn Z.",
    attempts: 28,
    dateSet: "2023-02-12T13:46:19Z",
    mostRecentAttempt: "2024-08-08T13:46:19Z",
    complete: false,
    dateComplete: "undefined",
    project: false,
    notes:
      "Working on linking the moves, getting closer on this one. Fun but tricky.",
    routeAttributes: ["Slab"],
  },
  {
    id: 8,
    name: "Desert Rose",
    img: "/generic_route_6.jpg",
    grade: "5.10d",
    gradeSystem: "YDS",
    difficulty: 10,
    routeProtection: "Top Rope",
    holdColor: "Pink",
    holdType: "Jugs",
    gym: 8,
    setter: "William Y.",
    attempts: 21,
    dateSet: "2023-01-09T03:07:07Z",
    mostRecentAttempt: "2024-01-01T03:07:07Z",
    complete: true,
    dateComplete: "2024-01-01T03:52:07Z",
    project: false,
    notes: "Managed to get the send today! Holds were great.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 9,
    name: "Jade Gem",
    img: "/generic_route_9.jpg",
    grade: "V7",
    gradeSystem: "V",
    difficulty: 15,
    routeProtection: "Boulder",
    holdColor: "Light Green",
    holdType: "Volumes",
    gym: 9,
    setter: "Ava T.",
    attempts: 13,
    dateSet: "2023-09-02T19:35:50Z",
    mostRecentAttempt: "2024-11-20T19:35:50Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "Still a long-term project. The crimps are relentless, need a lot more work.",
    routeAttributes: ["Overhang", "Traverse"],
  },
  {
    id: 10,
    name: "Silver Stream",
    img: "/generic_route_1.jpg",
    grade: "5.12a",
    gradeSystem: "YDS",
    difficulty: 15,
    routeProtection: "Lead",
    holdColor: "Grey",
    holdType: "Pinches",
    gym: 10,
    setter: "Harper P.",
    attempts: 25,
    dateSet: "2023-06-03T02:08:50Z",
    mostRecentAttempt: "2024-08-20T02:08:50Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "Can't quite get the last move on Silver Stream. Super fun but challenging, getting closer.",
    routeAttributes: ["Arete"],
  },
  {
    id: 11,
    name: "Aqua Flow",
    img: "/generic_route_2.jpg",
    grade: "8a",
    gradeSystem: "French",
    difficulty: 20,
    routeProtection: "Lead",
    holdColor: "Teal",
    holdType: "Crimps",
    gym: 1,
    setter: "Charlotte U.",
    attempts: 18,
    dateSet: "2023-02-17T06:01:21Z",
    mostRecentAttempt: "2024-03-24T06:01:21Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "This Aqua Flow is a beast! Still projecting the crux, needs more finger strength.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 12,
    name: "Forest Whisper",
    img: "/generic_route_7.jpg",
    grade: "V4",
    gradeSystem: "V",
    difficulty: 9,
    routeProtection: "Boulder",
    holdColor: "Brown",
    holdType: "Slopers",
    gym: 2,
    setter: "Alexander R.",
    attempts: 29,
    dateSet: "2023-04-09T03:31:07Z",
    mostRecentAttempt: "2024-09-02T03:31:07Z",
    complete: true,
    dateComplete: "2024-09-02T04:20:07Z",
    project: false,
    notes: "Managed to get the send today! Holds were great.",
    routeAttributes: ["Slab"],
  },
  {
    id: 13,
    name: "Marble Wall",
    img: "/generic_route_5.jpg",
    grade: "5.13a",
    gradeSystem: "YDS",
    difficulty: 19,
    routeProtection: "Lead",
    holdColor: "White",
    holdType: "Crimps",
    gym: 3,
    setter: "Michael X.",
    attempts: 21,
    dateSet: "2022-09-15T15:24:08Z",
    mostRecentAttempt: "2024-09-22T15:24:08Z",
    complete: false,
    dateComplete: "undefined",
    project: false,
    notes:
      "Making slow progress on Marble Wall. That dyno is a commitment, still working on the landing.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 14,
    name: "Shadow Dancer",
    img: "/generic_route_3.jpg",
    grade: "5.10c",
    gradeSystem: "YDS",
    difficulty: 9,
    routeProtection: "Top Rope",
    holdColor: "Black",
    holdType: "Jugs",
    gym: 4,
    setter: "Emma K.",
    attempts: 1,
    dateSet: "2024-05-02T05:35:10Z",
    mostRecentAttempt: "2025-05-19T05:35:10Z",
    complete: true,
    dateComplete: "2025-05-19T06:21:10Z",
    project: false,
    notes: "Sent this one! Flowy and fun, felt solid. Good warm-up route.",
    routeAttributes: ["Traverse"],
  },
  {
    id: 15,
    name: "Crimson Caverns",
    img: "/generic_route_6.jpg",
    grade: "V8",
    gradeSystem: "V",
    difficulty: 17,
    routeProtection: "Boulder",
    holdColor: "Red",
    holdType: "Pinches",
    gym: 5,
    setter: "Liam Q.",
    attempts: 28,
    dateSet: "2022-10-14T03:30:19Z",
    mostRecentAttempt: "2024-03-24T03:30:19Z",
    complete: false,
    dateComplete: "undefined",
    project: false,
    notes:
      "Still a long-term project. The crimps are relentless, need a lot more work.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 16,
    name: "Sandy Dune",
    img: "/generic_route_8.jpg",
    grade: "5.8",
    gradeSystem: "YDS",
    difficulty: 5,
    routeProtection: "Top Rope",
    holdColor: "Tan",
    holdType: "Jugs",
    gym: 6,
    setter: "Isabella V.",
    attempts: 19,
    dateSet: "2024-02-11T09:37:05Z",
    mostRecentAttempt: "2025-05-17T09:37:05Z",
    complete: true,
    dateComplete: "2025-05-17T10:14:05Z",
    project: false,
    notes:
      "Cracked it! The beta clicked after a few tries. Really enjoyed this one.",
    routeAttributes: ["Inside Corner"],
  },
  {
    id: 17,
    name: "Electric Current",
    img: "/generic_route_9.jpg",
    grade: "5.14a",
    gradeSystem: "YDS",
    difficulty: 23,
    routeProtection: "Lead",
    holdColor: "Light Blue",
    holdType: "Crimps",
    gym: 7,
    setter: "Evelyn Z.",
    attempts: 28,
    dateSet: "2022-09-19T06:54:19Z",
    mostRecentAttempt: "2024-02-27T06:54:19Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "This Electric Current is a beast! Still projecting the crux, needs more finger strength.",
    routeAttributes: ["Overhang", "Arete"],
  },
  {
    id: 18,
    name: "Crimson Tide",
    img: "/generic_route_4.jpg",
    grade: "V6",
    gradeSystem: "V",
    difficulty: 13,
    routeProtection: "Boulder",
    holdColor: "Red",
    holdType: "Slopers",
    gym: 8,
    setter: "William Y.",
    attempts: 10,
    dateSet: "2023-08-01T14:48:30Z",
    mostRecentAttempt: "2025-05-23T14:48:30Z",
    complete: false,
    dateComplete: "undefined",
    project: false,
    notes:
      "Felt a bit pumped on the last section. Still a fun project to try and flash.",
    routeAttributes: ["Traverse"],
  },
  {
    id: 19,
    name: "Midnight Crack",
    img: "/generic_route_1.jpg",
    grade: "7b+",
    gradeSystem: "French",
    difficulty: 17,
    routeProtection: "Lead",
    holdColor: "Black",
    holdType: "Cracks",
    gym: 9,
    setter: "Ava T.",
    attempts: 25,
    dateSet: "2023-11-20T17:19:30Z",
    mostRecentAttempt: "2024-07-28T17:19:30Z",
    complete: false,
    dateComplete: "undefined",
    project: false,
    notes:
      "Making slow progress on Midnight Crack. That dyno is a commitment, still working on the landing.",
    routeAttributes: ["Crack"],
  },
  {
    id: 20,
    name: "Sunstone Slab",
    img: "/generic_route_2.jpg",
    grade: "5.9",
    gradeSystem: "YDS",
    difficulty: 6,
    routeProtection: "Top Rope",
    holdColor: "Orange",
    holdType: "Crimps",
    gym: 10,
    setter: "Harper P.",
    attempts: 23,
    dateSet: "2023-05-09T08:08:42Z",
    mostRecentAttempt: "2025-01-20T08:08:42Z",
    complete: true,
    dateComplete: "2025-01-20T08:52:42Z",
    project: false,
    notes: "Sent this one! Flowy and fun, felt solid. Good warm-up route.",
    routeAttributes: ["Slab"],
  },
  {
    id: 21,
    name: "Copper Vein",
    img: "/generic_route_5.jpg",
    grade: "V9",
    gradeSystem: "V",
    difficulty: 19,
    routeProtection: "Boulder",
    holdColor: "Brown",
    holdType: "Volumes",
    gym: 1,
    setter: "Charlotte U.",
    attempts: 20,
    dateSet: "2023-01-20T06:23:44Z",
    mostRecentAttempt: "2024-03-22T06:23:44Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "Still a long-term project. The crimps are relentless, need a lot more work.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 22,
    name: "Skyline Ridge",
    img: "/generic_route_7.jpg",
    grade: "5.11d",
    gradeSystem: "YDS",
    difficulty: 14,
    routeProtection: "Lead",
    holdColor: "Blue",
    holdType: "Slopers",
    gym: 2,
    setter: "Alexander R.",
    attempts: 29,
    dateSet: "2023-07-25T11:43:08Z",
    mostRecentAttempt: "2024-11-20T11:43:08Z",
    complete: false,
    dateComplete: "undefined",
    project: false,
    notes:
      "Felt a bit pumped on the last section. Still a fun project to try and flash.",
    routeAttributes: ["Arete", "Traverse"],
  },
  {
    id: 23,
    name: "Whispering Winds",
    img: "/generic_route_3.jpg",
    grade: "6b",
    gradeSystem: "French",
    difficulty: 9,
    routeProtection: "Top Rope",
    holdColor: "Light Blue",
    holdType: "Jugs",
    gym: 3,
    setter: "Michael X.",
    attempts: 13,
    dateSet: "2024-01-21T02:07:44Z",
    mostRecentAttempt: "2025-06-03T02:07:44Z",
    complete: true,
    dateComplete: "2025-06-03T02:30:44Z",
    project: false,
    notes: "Sent this one! Flowy and fun, felt solid. Good warm-up route.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 24,
    name: "Crimson Dream",
    img: "/generic_route_8.jpg",
    grade: "5.12b",
    gradeSystem: "YDS",
    difficulty: 16,
    routeProtection: "Lead",
    holdColor: "Red",
    holdType: "Crimps",
    gym: 4,
    setter: "Emma K.",
    attempts: 27,
    dateSet: "2023-09-02T16:51:39Z",
    mostRecentAttempt: "2024-05-18T16:51:39Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "This Crimson Dream is a beast! Still projecting the crux, needs more finger strength.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 25,
    name: "Green Goblin",
    img: "/generic_route_6.jpg",
    grade: "V2",
    gradeSystem: "V",
    difficulty: 5,
    routeProtection: "Boulder",
    holdColor: "Green",
    holdType: "Jugs",
    gym: 5,
    setter: "Liam Q.",
    attempts: 25,
    dateSet: "2024-06-12T00:54:19Z",
    mostRecentAttempt: "2025-04-20T00:54:19Z",
    complete: true,
    dateComplete: "2025-04-20T01:43:19Z",
    project: false,
    notes: "Completed this route, felt pretty straightforward. Nice send.",
    routeAttributes: ["Inside Corner"],
  },
  {
    id: 26,
    name: "Pink Panther",
    img: "/generic_route_9.jpg",
    grade: "5.9",
    gradeSystem: "YDS",
    difficulty: 6,
    routeProtection: "Top Rope",
    holdColor: "Pink",
    holdType: "Slopers",
    gym: 6,
    setter: "Isabella V.",
    attempts: 8,
    dateSet: "2024-02-10T16:35:10Z",
    mostRecentAttempt: "2025-04-14T16:35:10Z",
    complete: true,
    dateComplete: "2025-04-14T17:15:10Z",
    project: false,
    notes: "Sent this one! Flowy and fun, felt solid. Good warm-up route.",
    routeAttributes: ["Slab"],
  },
  {
    id: 27,
    name: "Orange Orchard",
    img: "/generic_route_1.jpg",
    grade: "7a+",
    gradeSystem: "French",
    difficulty: 15,
    routeProtection: "Lead",
    holdColor: "Orange",
    holdType: "Pinches",
    gym: 7,
    setter: "Evelyn Z.",
    attempts: 9,
    dateSet: "2023-05-18T23:59:39Z",
    mostRecentAttempt: "2024-07-28T23:59:39Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "Can't quite get the last move on Orange Orchard. Super fun but challenging, getting closer.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 28,
    name: "Black Diamond",
    img: "/generic_route_2.jpg",
    grade: "5.15a",
    gradeSystem: "YDS",
    difficulty: 27,
    routeProtection: "Lead",
    holdColor: "Black",
    holdType: "Crimps",
    gym: 8,
    setter: "William Y.",
    attempts: 28,
    dateSet: "2022-12-07T05:39:19Z",
    mostRecentAttempt: "2024-02-09T05:39:19Z",
    complete: false,
    dateComplete: "undefined",
    project: false,
    notes:
      "Still a long-term project. The crimps are relentless, need a lot more work.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 29,
    name: "Yellow Brick Road",
    img: "/generic_route_4.jpg",
    grade: "V0",
    gradeSystem: "V",
    difficulty: 1,
    routeProtection: "Boulder",
    holdColor: "Yellow",
    holdType: "Jugs",
    gym: 9,
    setter: "Ava T.",
    attempts: 2,
    dateSet: "2024-02-07T09:30:19Z",
    mostRecentAttempt: "2025-06-21T09:30:19Z",
    complete: true,
    dateComplete: "2025-06-21T09:56:19Z",
    project: false,
    notes: "Completed this route, felt pretty straightforward. Nice send.",
    routeAttributes: ["Chimney"],
  },
  {
    id: 30,
    name: "White Knight",
    img: "/generic_route_5.jpg",
    grade: "5.10b",
    gradeSystem: "YDS",
    difficulty: 8,
    routeProtection: "Lead",
    holdColor: "White",
    holdType: "Slopers",
    gym: 10,
    setter: "Harper P.",
    attempts: 20,
    dateSet: "2023-09-06T10:49:19Z",
    mostRecentAttempt: "2025-03-29T10:49:19Z",
    complete: true,
    dateComplete: "2025-03-29T11:40:19Z",
    project: false,
    notes: "Managed to get the send today! Holds were great.",
    routeAttributes: ["Arete"],
  },
  {
    id: 31,
    name: "Crystal Clear",
    img: "/generic_route_6.jpg",
    grade: "8c",
    gradeSystem: "French",
    difficulty: 24,
    routeProtection: "Lead",
    holdColor: "Teal",
    holdType: "Crimps",
    gym: 1,
    setter: "Charlotte U.",
    attempts: 27,
    dateSet: "2023-10-18T20:30:19Z",
    mostRecentAttempt: "2025-05-13T20:30:19Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "Still a long-term project. The crimps are relentless, need a lot more work.",
    routeAttributes: ["Overhang", "Traverse"],
  },
  {
    id: 32,
    name: "Inferno Crack",
    img: "/generic_route_7.jpg",
    grade: "5.13d",
    gradeSystem: "YDS",
    difficulty: 22,
    routeProtection: "Lead",
    holdColor: "Red",
    holdType: "Cracks",
    gym: 2,
    setter: "Alexander R.",
    attempts: 26,
    dateSet: "2022-09-05T01:35:10Z",
    mostRecentAttempt: "2024-03-08T01:35:10Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "This Inferno Crack is a beast! Still projecting the crux, needs more finger strength.",
    routeAttributes: ["Crack"],
  },
  {
    id: 33,
    name: "Cobalt Dream",
    img: "/generic_route_8.jpg",
    grade: "V10",
    gradeSystem: "V",
    difficulty: 21,
    routeProtection: "Boulder",
    holdColor: "Blue",
    holdType: "Slopers",
    gym: 3,
    setter: "Michael X.",
    attempts: 13,
    dateSet: "2023-04-20T05:35:10Z",
    mostRecentAttempt: "2024-05-18T05:35:10Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "Can't quite get the last move on Cobalt Dream. Super fun but challenging, getting closer.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 34,
    name: "Pistachio Route",
    img: "/generic_route_9.jpg",
    grade: "5.11a",
    gradeSystem: "YDS",
    difficulty: 11,
    routeProtection: "Lead",
    holdColor: "Green",
    holdType: "Pinches",
    gym: 4,
    setter: "Emma K.",
    attempts: 10,
    dateSet: "2023-11-20T08:24:08Z",
    mostRecentAttempt: "2025-06-11T08:24:08Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "Still figuring out the top sequence on Pistachio Route. Good progress though.",
    routeAttributes: ["Inside Corner"],
  },
  {
    id: 35,
    name: "Golden Grip",
    img: "/generic_route_1.jpg",
    grade: "6a+",
    gradeSystem: "French",
    difficulty: 8,
    routeProtection: "Top Rope",
    holdColor: "Yellow",
    holdType: "Crimps",
    gym: 5,
    setter: "Liam Q.",
    attempts: 18,
    dateSet: "2024-03-01T20:30:19Z",
    mostRecentAttempt: "2025-02-12T20:30:19Z",
    complete: true,
    dateComplete: "2025-02-12T20:47:19Z",
    project: false,
    notes: "Managed to get the send today! Holds were great.",
    routeAttributes: ["Slab"],
  },
  {
    id: 36,
    name: "Onyx Odyssey",
    img: "/generic_route_2.jpg",
    grade: "5.14c",
    gradeSystem: "YDS",
    difficulty: 25,
    routeProtection: "Lead",
    holdColor: "Black",
    holdType: "Slopers",
    gym: 6,
    setter: "Isabella V.",
    attempts: 28,
    dateSet: "2022-09-01T04:22:20Z",
    mostRecentAttempt: "2024-01-21T04:22:20Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "Still a long-term project. The crimps are relentless, need a lot more work.",
    routeAttributes: ["Overhang", "Arete"],
  },
  {
    id: 37,
    name: "Crimson Vortex",
    img: "/generic_route_3.jpg",
    grade: "V7",
    gradeSystem: "V",
    difficulty: 15,
    routeProtection: "Boulder",
    holdColor: "Red",
    holdType: "Volumes",
    gym: 7,
    setter: "Evelyn Z.",
    attempts: 22,
    dateSet: "2023-01-09T16:51:39Z",
    mostRecentAttempt: "2024-05-20T16:51:39Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "Can't quite get the last move on Crimson Vortex. Super fun but challenging, getting closer.",
    routeAttributes: ["Traverse"],
  },
  {
    id: 38,
    name: "Emerald Edge",
    img: "/generic_route_4.jpg",
    grade: "5.12c",
    gradeSystem: "YDS",
    difficulty: 17,
    routeProtection: "Lead",
    holdColor: "Green",
    holdType: "Crimps",
    gym: 8,
    setter: "William Y.",
    attempts: 29,
    dateSet: "2022-09-05T08:08:42Z",
    mostRecentAttempt: "2024-01-01T08:08:42Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "This Emerald Edge is a beast! Still projecting the crux, needs more finger strength.",
    routeAttributes: ["Arete"],
  },
  {
    id: 39,
    name: "Purple Palace",
    img: "/generic_route_5.jpg",
    grade: "7c",
    gradeSystem: "French",
    difficulty: 18,
    routeProtection: "Lead",
    holdColor: "Purple",
    holdType: "Jugs",
    gym: 9,
    setter: "Ava T.",
    attempts: 22,
    dateSet: "2023-01-09T03:31:07Z",
    mostRecentAttempt: "2024-04-14T03:31:07Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "Making slow progress on Purple Palace. That dyno is a commitment, still working on the landing.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 40,
    name: "Silver Serpent",
    img: "/generic_route_6.jpg",
    grade: "5.10a",
    gradeSystem: "YDS",
    difficulty: 7,
    routeProtection: "Top Rope",
    holdColor: "Grey",
    holdType: "Slopers",
    gym: 10,
    setter: "Harper P.",
    attempts: 13,
    dateSet: "2024-01-21T15:24:08Z",
    mostRecentAttempt: "2025-06-03T15:24:08Z",
    complete: true,
    dateComplete: "2025-06-03T16:15:08Z",
    project: false,
    notes: "Sent this one! Flowy and fun, felt solid. Good warm-up route.",
    routeAttributes: ["Slab"],
  },
  {
    id: 41,
    name: "Crimson Canyon",
    img: "/generic_route_7.jpg",
    grade: "V5",
    gradeSystem: "V",
    difficulty: 11,
    routeProtection: "Boulder",
    holdColor: "Red",
    holdType: "Pinches",
    gym: 1,
    setter: "Charlotte U.",
    attempts: 29,
    dateSet: "2023-07-28T09:37:05Z",
    mostRecentAttempt: "2025-01-21T09:37:05Z",
    complete: false,
    dateComplete: "undefined",
    project: false,
    notes:
      "Still figuring out the top sequence on Crimson Canyon. Good progress though.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 42,
    name: "Golden Gate",
    img: "/generic_route_8.jpg",
    grade: "5.11b",
    gradeSystem: "YDS",
    difficulty: 12,
    routeProtection: "Lead",
    holdColor: "Yellow",
    holdType: "Slopers",
    gym: 2,
    setter: "Alexander R.",
    attempts: 28,
    dateSet: "2023-05-18T05:35:10Z",
    mostRecentAttempt: "2024-08-20T05:35:10Z",
    complete: false,
    dateComplete: "undefined",
    project: false,
    notes:
      "Felt a bit pumped on the last section. Still a fun project to try and flash.",
    routeAttributes: ["Arete"],
  },
  {
    id: 43,
    name: "Azure Abyss",
    img: "/generic_route_9.jpg",
    grade: "7b",
    gradeSystem: "French",
    difficulty: 16,
    routeProtection: "Lead",
    holdColor: "Light Blue",
    holdType: "Crimps",
    gym: 3,
    setter: "Michael X.",
    attempts: 21,
    dateSet: "2023-11-20T11:58:39Z",
    mostRecentAttempt: "2024-07-28T11:58:39Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "Making slow progress on Azure Abyss. That dyno is a commitment, still working on the landing.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 44,
    name: "Crimson Peak",
    img: "/generic_route_1.jpg",
    grade: "5.10d",
    gradeSystem: "YDS",
    difficulty: 10,
    routeProtection: "Top Rope",
    holdColor: "Red",
    holdType: "Jugs",
    gym: 4,
    setter: "Emma K.",
    attempts: 28,
    dateSet: "2024-01-21T06:01:21Z",
    mostRecentAttempt: "2025-04-14T06:01:21Z",
    complete: true,
    dateComplete: "2025-04-14T06:29:21Z",
    project: false,
    notes:
      "Cracked it! The beta clicked after a few tries. Really enjoyed this one.",
    routeAttributes: ["Inside Corner"],
  },
  {
    id: 45,
    name: "Forest Fern",
    img: "/generic_route_2.jpg",
    grade: "V3",
    gradeSystem: "V",
    difficulty: 7,
    routeProtection: "Boulder",
    holdColor: "Green",
    holdType: "Slopers",
    gym: 5,
    setter: "Liam Q.",
    attempts: 17,
    dateSet: "2024-02-11T13:46:19Z",
    mostRecentAttempt: "2025-05-19T13:46:19Z",
    complete: true,
    dateComplete: "2025-05-19T14:14:19Z",
    project: false,
    notes: "Completed this route, felt pretty straightforward. Nice send.",
    routeAttributes: ["Slab"],
  },
  {
    id: 46,
    name: "Sunstone Path",
    img: "/generic_route_3.jpg",
    grade: "5.9",
    gradeSystem: "YDS",
    difficulty: 6,
    routeProtection: "Top Rope",
    holdColor: "Orange",
    holdType: "Crimps",
    gym: 6,
    setter: "Isabella V.",
    attempts: 22,
    dateSet: "2023-09-06T03:07:07Z",
    mostRecentAttempt: "2024-11-20T03:07:07Z",
    complete: true,
    dateComplete: "2024-11-20T03:55:07Z",
    project: false,
    notes: "Sent this one! Flowy and fun, felt solid. Good warm-up route.",
    routeAttributes: ["Slab"],
  },
  {
    id: 47,
    name: "Violet Visions",
    img: "/generic_route_4.jpg",
    grade: "8a+",
    gradeSystem: "French",
    difficulty: 21,
    routeProtection: "Lead",
    holdColor: "Purple",
    holdType: "Pinches",
    gym: 7,
    setter: "Evelyn Z.",
    attempts: 25,
    dateSet: "2023-03-01T03:52:19Z",
    mostRecentAttempt: "2024-03-22T03:52:19Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "Can't quite get the last move on Violet Visions. Super fun but challenging, getting closer.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 48,
    name: "Crimson Cascade",
    img: "/generic_route_5.jpg",
    grade: "5.13a",
    gradeSystem: "YDS",
    difficulty: 19,
    routeProtection: "Lead",
    holdColor: "Red",
    holdType: "Crimps",
    gym: 8,
    setter: "William Y.",
    attempts: 27,
    dateSet: "2022-12-07T11:58:39Z",
    mostRecentAttempt: "2024-02-09T11:58:39Z",
    complete: false,
    dateComplete: "undefined",
    project: false,
    notes:
      "Still a long-term project. The crimps are relentless, need a lot more work.",
    routeAttributes: ["Overhang"],
  },
  {
    id: 49,
    name: "Teal Tornado",
    img: "/generic_route_6.jpg",
    grade: "V6",
    gradeSystem: "V",
    difficulty: 13,
    routeProtection: "Boulder",
    holdColor: "Teal",
    holdType: "Volumes",
    gym: 9,
    setter: "Ava T.",
    attempts: 29,
    dateSet: "2024-03-08T09:30:19Z",
    mostRecentAttempt: "2025-06-21T09:30:19Z",
    complete: false,
    dateComplete: "undefined",
    project: false,
    notes:
      "Still figuring out the top sequence on Teal Tornado. Good progress though.",
    routeAttributes: ["Traverse"],
  },
  {
    id: 50,
    name: "White Willow",
    img: "/generic_route_7.jpg",
    grade: "5.12a",
    gradeSystem: "YDS",
    difficulty: 15,
    routeProtection: "Lead",
    holdColor: "White",
    holdType: "Slopers",
    gym: 10,
    setter: "Harper P.",
    attempts: 23,
    dateSet: "2023-05-09T16:51:39Z",
    mostRecentAttempt: "2024-09-02T16:51:39Z",
    complete: false,
    dateComplete: "undefined",
    project: true,
    notes:
      "Can't quite get the last move on White Willow. Super fun but challenging, getting closer.",
    routeAttributes: ["Slab"],
  },
];

function convertJSONRoutesToRoutes(jsonRout: JSONClimbingRoute): ClimbingRoute {
  return {
    ...jsonRout,
    dateComplete:
      jsonRout.dateComplete === "undefined"
        ? undefined
        : new Date(jsonRout.dateComplete),
    dateSet: new Date(jsonRout.dateSet),
    mostRecentAttempt:
      jsonRout.mostRecentAttempt === "undefined"
        ? undefined
        : new Date(jsonRout.mostRecentAttempt),
    routeProtection: jsonRout.routeProtection as routeProtection,
    holdType: jsonRout.holdType as holdType,
    // gym: jsonRout.gym.toString(),
  };
}

export let TEMP_CLIMBING_ROUTES: ClimbingRoute[] =
  JSON_TEMP_CLIMBING_ROUTES.map(convertJSONRoutesToRoutes);
